award/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    url('^$', views.project, name='project'),
    url(r'^search/', views.search_results, name='search_results'),
    url(r'^new/project$', views.new_project, name='new_project'),
    url(r'^user/profile/', views.profile, name='profile'),
    url(r'^new/profile/$', views.update_profile, name='new_profile'),
    url(r'^new/rate$', views.rate, name='rate'),
    url(r'^api/profile/$', views.ProfileList.as_view()),
    url(r'^api/project/$', views.ProjectList.as_view())

]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

awardp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('award.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'})
]

award/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    profile_photo = models.ImageField(upload_to = 'profile/')
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.TextField()
    contact = models.TextField()

    def __str__(self):
        return f'{self.user.username} Profile'

    def save_profile(self):
        self.save()

    @classmethod
    def save_profile(cls):
        profile=cls.objects.filter()
        return profile

    def update_profile(self):
        self.update()

    def delete_profile():
        self.delete()

class Project(models.Model):
    title = models.CharField(max_length = 60)
    image = models.ImageField(upload_to = 'image/')
    description = models.TextField()
    link = models.CharField(max_length = 300)
    user = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    pub_date = models.DateTimeField(auto_now_add=True, null=True)

    def save_project(self):
        self.save()

    @classmethod
    def save_project(cls):
        projects=cls.objects.filter()
        return projects
    
    @classmethod
    def search_by_title(cls,search_term):
        projects = cls.objects.filter(title__icontains=search_term)
        return projects

    def update_project(self):
        self.update()

    def delete_project():
        self.delete()


RATE_CHOICES = [
    (1,'1- I did not like it'),
    (2,'2- I did not like it'),
    (3,'3- I did not like it'),
    (4,'4- Okay'),
    (5,'5- Okay'),
    (6,'6- Okay'),
    (7,'7- Above Average'),
    (8,'8- Great'),
    (9,'9- Great'),
    (10,'10- Master Piece!'),
]

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=3000, blank=True)
    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES)
    likes = models.PositiveIntegerField(default=0)
    unlikes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user.username

award/forms.py
from django import forms
from .models import Profile, Project, Review, RATE_CHOICES
from django.contrib.auth.models import User

class NewProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude = ['user']
    
class UpdateUser(forms.ModelForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username', 'email']

class UpdateProfile(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

class RateForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'materialize-textarea'}), required=False)
    rate = forms.ChoiceField(choices=RATE_CHOICES,widget=forms.Select(),required=True)

    class Meta:
        model = Review
        fields = ('text', 'rate')

award/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http  import HttpResponse
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from django.contrib.auth.decorators import login_required
from .models import Profile, Project, Review
from .serializer import ProfileSerializer, ProjectSerializer
from .forms import NewProjectForm, UpdateProfile, UpdateUser, RateForm

# Create your views here.
@login_required(login_url='/accounts/login/')
def project(request):
    profile=Profile.objects.all()
    projects=Project.objects.all()
    return render(request, 'project.html',{"profile":profile, "projects":projects})

def profile(request):
    return render(request, 'profile.html')

@login_required(login_url='/accounts/login/')
def search_results(request):

    if 'project' in request.GET and request.GET["project"]:
        search_term = request.GET.get("project")
        searched_projects = Project.search_by_title(search_term)
        message = f"{search_term}"

        return render(request, 'search.html',{"message":message,"projects": searched_projects})

    else:
        message = "You haven't searched for any term"
        return render(request, 'search.html',{"message":message})

@login_required(login_url='/accounts/login/')
def new_project(request):
    current_user = request.user
    if request.method == 'POST':
        form = NewProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.user = current_user
            project.save()
        return redirect('project')
        
    else:
        form = NewProjectForm()
    return render(request, 'new_project.html', {"form":form, "current_user":current_user})

@login_required(login_url='/accounts/login/')
def update_profile(request):
    profile = Profile(user=request.user)
    update_user=UpdateUser(request.POST,instance=request.user)
    update_profile=UpdateProfile(request.POST,request.FILES,instance=profile)
    if update_user.is_valid() and update_profile.is_valid():
        update_user.save()
        update_profile.save()
        return redirect('profile')
    else:
        update_user=UpdateUser(instance=request.user)
        update_profile=UpdateProfile(instance=profile)
    return render(request, 'edit.html',{'update_user':update_user,'update_profile':update_profile})

# @login_required(login_url='login')
# def edit_profile(request, username):
#     user = User.objects.get(username=username)
#     if request.method == 'POST':
#         user_form = UpdateUser(request.POST, instance=request.user)
#         prof_form = UpdateProfile(request.POST, request.FILES, instance=request.user.profile)
#         if user_form.is_valid() and prof_form.is_valid():
#             user_form.save()
#             prof_form.save()
#             return redirect('profile', user.username)
#     else:
#         uform = UpdateUser(instance=request.user)
#         pform = UpdateProfile(instance=request.user.profile)
#     params = {
#         'user_form': uform,
#         'prof_form': pform,
#     }
#     return render(request, 'edit.html', params)

@login_required(login_url='/accounts/login/')
def rate(request):
    return render(request, 'rate.html')
    # project = Project.objects.get(request.user.project)
    # user = request.user

    # if request.method == 'POST':
    #     form = RateForm(request.POST)
    #     if form.is_valid():
    #         rate = form.save(commit=False)
    #         rate.user = user
    #         rate.movie = movie
    #         rate.save()
    #         return HttpResponseRedirect(reverse('profile', args=[project_id]))

    #     else:
    #         form = RateForm()
    #         template = loader.get_template('rate.html')
    #         context = {
    #         'form':form,
    #         'project': project,
    #         }

    #     return HttpResponse(template.render(context, request))

class ProfileList(APIView):
    def get(self, request, format=None):
        all_profile = Profile.objects.all()
        serializers = ProfileSerializer(all_profile, many=True)
        return Response(serializers.data)

class ProjectList(APIView):
    def get(self, request, format=None):
        all_project = Project.objects.all()
        serializers = ProjectSerializer(all_project, many=True)
        return Response(serializers.data)

    

award/templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>Project Review- {{title}}</title>
    {% else %}
    <title>Project Review</title>
    {% endif %}


    {% block styles %}
    {% bootstrap_css %}
    {% endblock %}
</head>

<body style="background-image: url('https://free4kwallpapers.com/uploads/originals/2015/08/09/cool-black-backgrounds.jpg'); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">
    {% include 'navbar.html' %}

    <div class="container">
        {% block content %} {% endblock %}
    </div>

</body>
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% bootstrap_javascript %}
{% endblock %}

</html>

award/templates/edit.html
{%extends "base.html"%}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <div class="row">
    <!-- Empty div -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="text-center">Edit Profile</h3>
        </div>
        <div class="panel-body">

          <form  action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form update_user%}
            {% bootstrap_form update_profile%}
            <div class="form-group">
              <input type="submit" class="btn btn-primary btn-sm float-right" value="Update">
            </div>

            <input type="hidden" name="next" value="{{next}}">

          </form>

        </div>

      </div>

    </div>
    <!-- empty div -->
    <div class="col-md-3"></div>
  </div>
</div>

{% endblock %}

award/templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Review</title>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'project' %}" style="color: cornsilk;"><strong>Project
                        Review</strong></a>
            </div>
            <div style="margin-top: 15px;" class="content">
                {% if user.is_authenticated %}
                <a style="padding-left: 50px ; color: brown;" href="{% url 'project' %}"><i class="glyphicon glyphicon-home"></i> Home</a>
                <a style="padding-left: 20px ; color: brown;" href="{% url 'profile' %}"><i class="glyphicon glyphicon-user"></i> Profile</a>
                <a style="padding-left: 20px ; color: brown;" href="{% url 'new_project' %}"><i class="glyphicon glyphicon-plus"></i> Post</a>
                <span class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" style="color: brown; padding-left: 20px;" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="glyphicon glyphicon-menu-down"></i>API
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" style="color: brown;" href="/api/profile/?format=json"><strong>Profile</strong></a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" style="color: brown;" href="/api/project/?format=json"><strong>Project</strong></a>
                    </div>
                </span>
        
                <!-- Adding a search form  -->
                <div class="col-sm-4 col-md-4 navbar-right">

                    <form class="navbar-form" role="search" action="{% url 'search_results' %}">

                        <div class="input-group" style="margin-top: 0px;">
                            <input type="text" class="form-control" placeholder="Search Project Title" name="project">
                            <div class="input-group-btn">
                                <button style="color: brown;" class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>

                    </form>
                </div>
                <!-- search form end -->
                <a style=" padding-left: 20px; color: brown;" href="/logout"><i class="glyphicon glyphicon-log-out"></i> Log Out</a>
                {% else %}
                <a style="padding-left: 20px;color: brown;" href="/accounts/login"><i class="glyphicon glyphicon-log-in"></i> Log In</a>
                {% endif %}
            </div>
        </div>
    </nav>
</body>

</html>

award/templates/new_project.html
{% load bootstrap3 %} {% load staticfiles %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>New Project</title>
        {{form.media}}

        {% block styles %} {% bootstrap_css %}
        <link rel="stylesheet" href="{% static 'css/posts.css' %}"> {% endblock %}

    </head>

    <body style="background-image: url('https://free4kwallpapers.com/uploads/originals/2015/08/09/cool-black-backgrounds.jpg'); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; color: brown;">
        {% include 'navbar.html' %}
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h4 style="color: cornsilk;">Add Project</h4>
                    <form  action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        {% bootstrap_form form%}
                        <input type="submit" class="btn btn-danger btn-sm" value="Post">
                    </form>
                    
                    {% block scripts %}
                    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                    {% bootstrap_javascript %} {% endblock %}
                    
                </body>
                
            </html>
                </div>
            </div>
        </div>
        

award/templates/profile.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
   <div class="row">
      <div class="col-md-12">
         <div class="jumbotron">
            <strong style="font-size: 50px; padding-left: 30px;">{{user.username}}</strong><hr>
            <span style="padding-left: 30px;">{{user.email}}</span><br>

         </div>
      </div>
   </div>
</div> 

<!-- <style>
   .wrimagecard-topimage_header {
      padding: 20px;
   }

   .wrimagecard-topimage_title {
      padding-left: 20px;
      height: 50px;
      padding-bottom: 5px;
   }
</style>
<div class="container">
   <div class="row">
      <div class="col-md-12">
         <div class="jumbotron">
            <img style="border-radius: 250px; width: 250px; height: 250px;" src="{{user.profile.profile_photo.url}}">
            <strong style="font-size: 50px; padding-left: 30px;">{{user.username}}</strong>
            <hr>
            <h5>Bio</h5>
            <p>{{user.profile.bio}}</p>
            <span>{{user.email}}</span><br>
            <a style="color: brown;" href="{% url 'new_profile' %}"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
         </div>
      </div>
   </div>
   {%for image in user.project_set.all%}
   <div class="col-sm-4">
      <div class="wrimagecard wrimagecard-topimage" style="background-color:whitesmoke;">
         <h4
            style="color: whitesmoke; padding-left: 20px; padding-top: 10px; padding-bottom: 5px; background-color: brown;">
            {{image.title}}
         </h4>
         <small style="padding-left:20px ;">{{image.pub_date}}</small>
         <div class="wrimagecard-topimage_header">
            <img style="width: 308px; height: 200px;" class="img-responsive" src="{{image.image.url}}">
         </div>
         <div class="wrimagecard-topimage_title">
            <span style="color: brown;">Rating:</span><span style="color: purple;"><strong> 8
               </strong></span><span style="color: brown;">out of 10</span>

            <button type="button" style="color: whitesmoke; float: right; margin-right: 5px;"
               class="btn btn-danger btn-sm" data-toggle="modal" data-target="#myModal{{image.id}}">Details
            </button>
         </div>
      </div>
   </div>
   {% endfor %}
   <!-- Modal -->
   <!-- {%for image in user.project_set.all%}
   <div class="modal fade" id="myModal{{image.id}}" role="dialog">
      <div class="modal-dialog">
         <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
               <h4 class="modal-title" style="color: brown;">{{image.title}}</h4>
            </div>
            <div class="modal-body">
               <img style="width: 608px; height: 300px;" class="img-responsive" src="{{image.image.url}}">
               <p style="color: brown;">Description </p>
               <p>{{image.description}}</p>
               <a style="color: brown;" href="{{image.link}}">Visit Website <span class="glyphicon glyphicon-new-window"
                     aria-hidden="true"></span></a>
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
               <a class="btn btn-danger btn-sm" style="color: whitesmoke; float: right; margin-right: 20px;">Rate
               </a>
            </div>
         </div>
      </div>
   </div>
   {%endfor%}
</div>
</div>

{% endblock %} --> 

award/templates/project.html
{% extends 'base.html' %}
{% block content %}
{{block.super}}
<style>
    .wrimagecard-topimage_header {
        padding: 10px;
    }

    .wrimagecard-topimage_title {
        padding-left: 20px;
        height: 50px;
        padding-bottom: 5px;
    }
</style>
<div class="container-fluid">
    <div class="row">
       {% for project in projects %}
       {% for profile in profile %}
        <div class="col-md-4">
          <div class="wrimagecard wrimagecard-topimage" style="background-color:whitesmoke;">
             <h4
                style="color: whitesmoke; padding-left: 20px; padding-top: 10px; padding-bottom: 5px; background-color: brown"><img style="border-radius: 30px; width: 30px; height: 30px;" src="{{profile.profile_photo.url}}"> 
                {{project.user.username}}
             </h4>
      
             <h4
                style="color: brown; padding-left: 20px; padding-top: 10px;">
                {{project.title}}
             </h4>
             <small style="padding-left:20px ;">{{project.pub_date}}</small>
             <div class="wrimagecard-topimage_header">
                <img style="width: 328px; height: 200px;" class="img-responsive" src="{{project.image.url}}">
             </div>
             <div class="wrimagecard-topimage_title">
                <!-- <span style="color: brown;">Rating:</span><span style="color: purple;"><strong> 8
                </strong></span><span style="color: brown;">out of 10</span> -->
                <button type="button" style="color: whitesmoke; float: right; margin-right: 5px;"
                   class="btn btn-danger btn-sm" data-toggle="modal"
                   data-target="#myModal{{project.id}}"><i class="glyphicon glyphicon-info-sign"></i> Details
                </button>
             </div>
          </div>
        </div>
        <!-- Modal -->
         <div class="modal fade" id="myModal{{project.id}}" role="dialog">
            <div class="modal-dialog">
               <div class="modal-content">
                  <div class="modal-header">
                     <button type="button" class="close" data-dismiss="modal">&times;</button>
                     <h4 class="modal-title" style="color: brown;">{{project.title}}</h4>
                  </div>
                  <div class="modal-body">
                     <img style="width: 608px; height: 300px;" class="img-responsive" src="{{project.image.url}}">
                     <p style="color: brown;">Description </p>
                     <p>{{project.description}}</p>
                     <a style="color: brown;" href="{{project.link}}">Visit Website <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span></a>
                  </div>
                  <div class="modal-footer">
                     
                     <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
                     <a class="btn btn-danger btn-sm"
                       style="color: whitesmoke; float: right; margin-right: 20px;" href=" {% url 'rate'%}"><i class="glyphicon glyphicon-star"></i> Rate
                     </a>
                     
                  </div>
               </div>
            </div>
         </div>
         {% endfor %}
        {% endfor %}
    </div> 
</div>


{% endblock %}

award/templates/rate.html
{% extends 'base.html' %}
{% block content %}
{{block.super}}
<form style="color: brown;">
    <h4 style="color: cornsilk; background-color: brown;">Rate</h4>
    <p>Design</p><input type="number" name="num1" min='0' max='10' > <br>
    <p>Usability</p><input type="number" name="num2" min='0' max='10'> <br>
    <p>Content</p><input type="number" name="num3" min='0' max='10'><br><br>

    <button type="button" onclick="myFunction()" id="calc">Calculate</button><br><br>
    <p id="demo"></p>


    Average Score <output style="color: cornsilk;" id="avg"></output> <hr> <!-- output should not be in input type elements  -->
    Maximum Score <output style="color: cornsilk;" id="max"></output> <hr> <!-- output should not be in input type elements  -->
    Minimum Score <output style="color: cornsilk;" id="min"></output> <hr> <!-- output should not be in input type elements  -->
    <br><br>
</form>

<script>
    // Get references to the elements just once
    var num1 = document.querySelector("[name='num1']");
    var num2 = document.querySelector("[name='num2']");
    var num3 = document.querySelector("[name='num3']");

    var max = document.getElementById("max");
    var avg = document.getElementById("avg");
    var min = document.getElementById("min");

    var btn = document.getElementById("calc");

    // Set up your event handler(s) in JavaScript, not with HTML attributes
    btn.addEventListener("click", function () {
        maximum();
        average();
        minimum();
    });

    function myFunction() {
        var x, text;

        // Get the value of the input field with id="numb"
        x = document.getElementsByName("max","avg","min").value;

        // If x is Not a Number or less than one or greater than 10
        if (isNaN(x) || x < 1 || x > 10) {
            text = "Input not valid";
        } else {
            text = "Input OK";
        }
        document.getElementById("demo").innerHTML = text;
        }

    function maximum() {
        
        // You can't just set an element to a value. You have to set the content of the 
        // element to a value. Also, JavaScript provides a built-in Math object that
        // can get you the maximum number from a set of numbers. No if/then needed.
        max.textContent = Math.max(num1.value, num2.value, num3.value);
    }

    function average() {
        // Convert values to numbers and do math
        avg.textContent = (+num1.value + +num1.value + +num3.value) / 3
    }

    function minimum() {
        // You can't just set an element to a value. You have to set the content of the 
        // element to a value. Math can also get you the minimum number in a set:
        min.textContent = Math.min(num1.value, num2.value, num3.value);
    }
</script>

{% endblock %}

award/templates/search.html
{%extends 'base.html'%} 
{% block content %}
<style>
  .wrimagecard-topimage_header {
      padding: 20px;
  }

  .wrimagecard-topimage_title {
      padding-left: 20px;
      height: 50px;
      padding-bottom: 5px;
  }
</style>
<div class="container">

  <div class="row" style="color: cornsilk;">
    {% if projects%}
      <h4>Found {{ projects|length }} of searched term {{message}}.</h4>
    {% else %}
      <h4> Found 0 projects for the search term {{message}}.</h4>
    {% endif %}

  </div>

  <div class="row">

  {% if projects %}
    {% for project in projects %}
      <div class="col-sm-4">
        <div class="wrimagecard wrimagecard-topimage" style="background-color:whitesmoke;">
          <h4
             style="color: whitesmoke; padding-left: 20px; padding-top: 10px; padding-bottom: 5px; background-color: brown;">
             {{project.title}}
          </h4>
          <small style="padding-left:20px ;">{{project.pub_date}}</small>
          <div class="wrimagecard-topimage_header">
             <img style="width: 308px; height: 200px;" class="img-responsive" src="{{project.image.url}}">
          </div>
          <div class="wrimagecard-topimage_title">
             <span style="color: brown;">Rating:</span><span style="color: purple;"><strong> 8
             </strong></span><span style="color: brown;">out of 10</span>
             
             <button type="button" style="color: whitesmoke; float: right; margin-right: 5px;"
                class="btn btn-danger btn-sm" data-toggle="modal"
                data-target="#myModal{{project.id}}">Details
             </button>
          </div>
       </div>
     </div>
     <!-- Modal -->
      <div class="modal fade" id="myModal{{project.id}}" role="dialog">
         <div class="modal-dialog">
            <div class="modal-content">
               <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title" style="color: brown;">{{project.title}}</h4>
               </div>
               <div class="modal-body">
                  <img style="width: 608px; height: 300px;" class="img-responsive" src="{{project.image.url}}">
                  <p style="color: brown;">Description </p>
                  <p>{{project.description}}</p>
                  <a style="color: brown;" href="{{project.link}}">Visit Website <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span></a>
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Close</button>
                  <a class="btn btn-danger btn-sm" href="{% url 'rate' %}"
                     style="color: whitesmoke; float: right; margin-right: 20px;">Rate
                  </a>
               </div>
            </div>
         </div>
      </div>
      </div>
    {% endfor %}
  {% endif %}
  </div>
</div>
{% endblock %}

award/templates/update_profile.html
{%extends "base.html"%}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <div class="row">
    <!-- Empty div -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="text-center">Edit Profile</h3>
        </div>
        <div class="panel-body">

          <form  action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form update_user%}
            {% bootstrap_form update_profile%}
            <div class="form-group">
              <input type="submit" class="btn btn-primary btn-sm float-right" value="Update">
            </div>

            <input type="hidden" name="next" value="{{next}}">

          </form>

        </div>

      </div>

    </div>
    <!-- empty div -->
    <div class="col-md-3"></div>
  </div>
</div>

{% endblock %}